name: pylit 

channels:
  - defaults

dependencies:
  - python=3.8
  - pip
  - numpy
  - matplotlib
  - sphinx
  - scipy
  - ipykernel
  - sympy
  - numba
  - streamlit
  - pip:
    - streamlit_option_menu
    - plotly